import { NextResponse } from "next/server";
import { z } from "zod";
import { createCancelToken } from "@/lib/cancel-token";
import { deliverIntegrationEvent } from "@/lib/integrations/make";
import { createServiceClient } from "@/lib/supabase/service";

const schema=z.object({slug:z.string().min(3).max(50),serviceId:z.string().uuid(),startsAt:z.string().datetime({offset:true}),clientName:z.string().trim().min(2).max(120),clientPhone:z.string().trim().min(8).max(30),clientEmail:z.string().email().max(200).optional().or(z.literal("")),notes:z.string().max(500).optional().or(z.literal(""))});
const errors:Record<string,string>={free_plan_limit_reached:"Este profissional atingiu o limite mensal do plano Free.",slot_unavailable:"Esse horário acabou de ser reservado. Escolha outro.",schedule_block_conflict:"Horário indisponível.",outside_availability:"Horário fora da agenda do profissional.",service_not_found:"Serviço indisponível.",profile_not_found:"Profissional não encontrado."};
export async function POST(request:Request){let json:unknown;try{json=await request.json();}catch{return NextResponse.json({error:"JSON inválido"},{status:400});}const parsed=schema.safeParse(json);if(!parsed.success)return NextResponse.json({error:"Dados de agendamento inválidos"},{status:400});const d=parsed.data;const supabase=createServiceClient();const {data,error}=await supabase.rpc("book_appointment",{p_slug:d.slug,p_service_id:d.serviceId,p_starts_at:d.startsAt,p_client_name:d.clientName,p_client_phone:d.clientPhone,p_client_email:d.clientEmail||null,p_notes:d.notes||null});if(error){const known=Object.entries(errors).find(([key])=>error.message.includes(key));return NextResponse.json({error:known?.[1]||"Não foi possível concluir a reserva."},{status:error.message.includes("slot_unavailable")?409:400});}const row=data?.[0];if(!row)return NextResponse.json({error:"Reserva não criada"},{status:500});const exp=Math.floor(new Date(row.starts_at).getTime()/1000);const token=createCancelToken(row.appointment_id,exp);const base=process.env.NEXT_PUBLIC_APP_URL||new URL(request.url).origin;await deliverIntegrationEvent(row.integration_event_id).catch(()=>false);return NextResponse.json({appointmentId:row.appointment_id,startsAt:row.starts_at,endsAt:row.ends_at,timezone:row.timezone,cancelUrl:`${base}/cancel/${token}`},{status:201});}
