"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Service={id:string;name:string;description:string|null;duration_minutes:number;price_cents:number};
type Slot={starts_at:string;ends_at:string;label:string;timezone:string};

export default function BookingForm({slug,services}:{slug:string;services:Service[]}){
  const [serviceId,setServiceId]=useState(services[0]?.id||""); const [date,setDate]=useState(""); const [slots,setSlots]=useState<Slot[]>([]); const [selected,setSelected]=useState<Slot|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [success,setSuccess]=useState<{id:string;cancelUrl:string}|null>(null);
  const minDate=useMemo(()=>new Date().toISOString().slice(0,10),[]);
  useEffect(()=>{if(!serviceId||!date){setSlots([]);setSelected(null);return;}setLoading(true);setError("");fetch(`/api/availability?slug=${encodeURIComponent(slug)}&serviceId=${serviceId}&date=${date}`).then(r=>r.json().then(j=>({ok:r.ok,j}))).then(({ok,j})=>{if(!ok)throw new Error(j.error||"Falha ao carregar horários");setSlots(j.slots||[]);setSelected(null);}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[slug,serviceId,date]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected){setError("Escolha um horário.");return;}setLoading(true);setError("");const f=new FormData(e.currentTarget);const response=await fetch("/api/book",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({slug,serviceId,startsAt:selected.starts_at,clientName:f.get("name"),clientPhone:f.get("phone"),clientEmail:f.get("email"),notes:f.get("notes")})});const body=await response.json();if(!response.ok){setError(body.error||"Não foi possível reservar. Atualize os horários e tente novamente.");setLoading(false);return;}setSuccess({id:body.appointmentId,cancelUrl:body.cancelUrl});setLoading(false);}
  if(success)return <div className="card"><h2>Agendamento confirmado ✅</h2><p>Guarde seu link de cancelamento caso precise alterar seus planos.</p><a className="button secondary" href={success.cancelUrl}>Abrir link de cancelamento</a></div>;
  return <form onSubmit={submit} className="stack"><label>Serviço<select value={serviceId} onChange={e=>setServiceId(e.target.value)}>{services.map(s=><option key={s.id} value={s.id}>{s.name} · {s.duration_minutes} min · {(s.price_cents/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</option>)}</select></label><label>Data<input type="date" min={minDate} value={date} onChange={e=>setDate(e.target.value)} required/></label><div><strong>Horários disponíveis</strong><div className="slot-grid" style={{marginTop:8}}>{loading&&<span className="muted">Carregando...</span>}{!loading&&date&&!slots.length&&<span className="muted">Nenhum horário disponível.</span>}{slots.map(s=><button type="button" key={s.starts_at} className={selected?.starts_at===s.starts_at?"selected":""} onClick={()=>setSelected(s)}>{s.label}</button>)}</div></div><div className="grid"><label>Nome<input name="name" required maxLength={120}/></label><label>WhatsApp<input name="phone" required maxLength={30}/></label><label>E-mail (opcional)<input name="email" type="email" maxLength={200}/></label></div><label>Observação (opcional)<textarea name="notes" maxLength={500}/></label>{error&&<p className="error">{error}</p>}<button disabled={loading||!selected}>{loading?"Confirmando...":"Confirmar agendamento"}</button></form>;
}
